version: '2'
services:
  db:
    container_name: db
    image: mysql:5.7
    command: "--innodb_use_native_aio=0"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: root
        MYSQL_PASSWORD: root
    volumes:
        - ./data/:/var/lib/mysql
    ports:
        - "3306:3306"
  # web:
  #   container_name: php_web
  #   image: php:7.2.2-apache
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./www/:/var/www/html/
  #   ports:
  #     - "8080:80"
  #   stdin_open: true
  #   tty: true